### PR TITLE
fix some typos + message consistency

### PR DESCRIPTION
**Pull request by un1versal**
Feel free to review setting me right if I over-corrected something.

I tried making all messages have more consistency and fixed some capitalization in addition of typos.
Updated links etc.

Also in some messages updated from XBMC -> Kodi messages only though, shouldn't break anything but what do I know :tongue: 

Anywho have a look.

all of this because I wanted to add the actual names of files being cleaned out to the output, as currently you start a clean process and the output just says what the ID was, I would find it helpful to know what the filename/title is as ID on its own is meaningless and not human readable.

So was looking to make sense but I wasnt sure  so thats not here and I need to test.

### CODE REVIEW

**Comment by un1versal** [comment]
Since other scripts aren't as long, I thought I show them same love.

**Comment by un1versal** [comment]
@MilhouseVH have another quick look after review fixes.

**Comment by un1versal** [comment]
@MilhouseVH and that should be that, including serial killing ;)  have a look and see if thats enough gore for you :tongue:

**Comment by un1versal** [comment]
added some quick once over fixes for readme while I was waiting for Kodi to finish compiling

**Comment by MilhouseVH** [comment]
Thanks again. Hopefully Kodi PR8196 will be merged soon, and then I'll push out another update.

**Comment by un1versal** [comment]
yw, 

no idea how you merged this but it shows on my end as closed with unmerged commits.

your Git foo is weird. :D

**Comment by MilhouseVH** [comment]
I did it manually as I needed to update the version and changelog - I just followed the merging guidelines and added one extra commit (for version + changelog).

It looks like 3ef60d81c7bd3c58e0c0b05f2ac820eb4aee0664 is the commit I added with the version bump - perhaps closing this PR from that commit is what caused the problem in your repo?  However the merge commit 9aea7b75aa29dcd42b7c27f1e63898d2bdce0bd1 appears to have all your changes.

Probably my mistake for closing this PR from the wrong commit. I should probably have cherry picked or whatever git masters say.

**Comment by un1versal** [comment]
/me shrugs

its there thats what matters.

**Pull request closed without merging**
